import { WebchatClient } from './client.js';
import type {
  WebchatClientOptions,
  WebchatMessage,
  WebchatSettings,
  WebchatSettingsOverrides,
  WebchatStatus,
} from './types.js';
import { WIDGET_CSS } from './widget-styles.js';

export interface WebchatWidgetOptions extends Omit<WebchatClientOptions, 'autoConnect'> {
  /**
   * Presentation overrides on top of what the agent serves from
   * GET /widget/config (the settings made in the Chat Studio).
   */
  settings?: WebchatSettingsOverrides;
  /** Skip fetching the Studio's settings; use only `settings` and the defaults. */
  fetchConfig?: boolean;
  /** Header title. Shortcut for `settings.agentName`. */
  title?: string;
  /** Line under the title. Defaults to the connection status. */
  subtitle?: string;
  /** First message shown in the panel. Shortcut for `settings.greetings`. */
  greeting?: string;
  /** Shortcut for `settings.inputPlaceholder`. */
  placeholder?: string;
  /** Shortcut for `settings.position`. Ignored when `target` is given. */
  position?: 'bottom-right' | 'bottom-left';
  /** Mount inside this element (selector or node) instead of floating. */
  target?: string | HTMLElement;
  /** Show the floating launcher button. Defaults to true unless `target` is set. */
  launcher?: boolean;
  /** Start with the panel open. Defaults to false unless `target` is set. */
  open?: boolean;
  /** Connect immediately, or wait until the panel is first opened (default). */
  connectOn?: 'load' | 'open';
  /** Shortcut for `settings.colors.launcher` + `settings.colors.userBubble`. */
  accent?: string;
  /** localStorage namespace; change it to keep two embeds of one agent apart. */
  storageKey?: string;
}

export interface WebchatWidget {
  /** The underlying client, for anything the widget does not expose. */
  readonly client: WebchatClient;
  /** The settings in effect (server config + overrides). */
  readonly settings: WebchatSettings;
  open(): void;
  close(): void;
  toggle(): void;
  /** Forgets the conversation and starts a new session. */
  newChat(): void;
  /** Removes the widget from the page and disconnects. */
  destroy(): void;
}

const CHAT_ICON =
  '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" ' +
  'stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">' +
  '<path d="M21 11.5a8.4 8.4 0 0 1-9 8.4 9.9 9.9 0 0 1-4.2-.9L3 20.5l1.6-4.4A8.3 8.3 0 0 1 3.5 11.5 8.4 8.4 0 0 1 12 3a8.4 8.4 0 0 1 9 8.5z"/></svg>';
const SEND_ICON =
  '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" ' +
  'stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">' +
  '<path d="M21.5 2.5 11 13"/><path d="M21.5 2.5 15.5 21.5 11 13 2.5 8.5z"/></svg>';
const THUMB_UP =
  '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M7 11v9H4a1 1 0 0 1-1-1v-7a1 1 0 0 1 1-1zM7 11l4-7a2 2 0 0 1 2 2v4h5.5a2 2 0 0 1 2 2.3l-1.1 7a2 2 0 0 1-2 1.7H7"/></svg>';
const THUMB_DOWN =
  '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M17 13V4h3a1 1 0 0 1 1 1v7a1 1 0 0 1-1 1zM17 13l-4 7a2 2 0 0 1-2-2v-4H5.5a2 2 0 0 1-2-2.3l1.1-7a2 2 0 0 1 2-1.7H17"/></svg>';

export const DEFAULT_SETTINGS: WebchatSettings = {
  agentName: 'Chat',
  avatarUrl: '',
  launcherIconUrl: '',
  messageAvatarUrl: '',
  showAvatarInHeader: true,
  showAvatarOnMessages: false,
  showTools: false,
  bubbleStyle: 'round',
  teaser: { enabled: false, text: '👋 Have a question? I can help.', delayMs: 8000 },
  colors: { launcher: '#3b6cff', userBubble: '#3b6cff', assistantBubble: '#f1f4f9', background: '#ffffff', header: '#ffffff' },
  disclaimer: { enabled: false, text: 'Answers are generated by AI and may contain mistakes.' },
  inputPlaceholder: 'Type a message…',
  sendButtonText: 'Send',
  sendButtonStyle: 'text',
  greetings: [],
  timestamps: 'hidden',
  privacy: { enabled: false, title: 'Before we start', content: '', acceptLabel: 'I understand' },
  persistConversation: true,
  showNewChatButton: true,
  feedbackEnabled: true,
  position: 'bottom-right',
};

export function mergeSettings(base: WebchatSettings, ...patches: (WebchatSettingsOverrides | undefined)[]): WebchatSettings {
  let result = base;
  for (const patch of patches) {
    if (!patch) continue;
    result = {
      ...result,
      ...patch,
      teaser: { ...result.teaser, ...(patch.teaser ?? {}) },
      colors: { ...result.colors, ...(patch.colors ?? {}) },
      disclaimer: { ...result.disclaimer, ...(patch.disclaimer ?? {}) },
      privacy: { ...result.privacy, ...(patch.privacy ?? {}) },
      greetings: patch.greetings ?? result.greetings,
    };
  }
  return result;
}

function element<K extends keyof HTMLElementTagNameMap>(
  tag: K,
  className?: string,
  text?: string,
): HTMLElementTagNameMap[K] {
  const node = document.createElement(tag);
  if (className) node.className = className;
  if (text !== undefined) node.textContent = text;
  return node;
}

/** Black or white, whichever reads better on the given hex colour. */
function contrastColor(hex: string): string {
  const match = /^#?([0-9a-f]{6})$/i.exec(hex.trim());
  if (!match) return '#14161a';
  const value = Number.parseInt(match[1]!, 16);
  const r = (value >> 16) & 255;
  const g = (value >> 8) & 255;
  const b = value & 255;
  const luminance = (0.299 * r + 0.587 * g + 0.114 * b) / 255;
  return luminance > 0.6 ? '#14161a' : '#ffffff';
}

function initials(name: string): string {
  return name
    .split(/\s+/)
    .filter(Boolean)
    .slice(0, 2)
    .map((word) => word[0]!.toUpperCase())
    .join('') || '?';
}

function formatTime(iso: string, mode: WebchatSettings['timestamps']): string {
  if (mode === 'hidden') return '';
  const date = new Date(iso);
  if (Number.isNaN(date.getTime())) return '';
  return date.toLocaleTimeString(undefined, { hour: 'numeric', minute: '2-digit', hour12: mode === '12h' });
}

/* ── localStorage, all guarded: private mode and disabled storage must not break the chat ── */
interface StoredConversation {
  sessionId: string;
  messages: WebchatMessage[];
  updatedAt: string;
}
const CONVERSATION_MAX_AGE_MS = 7 * 24 * 60 * 60 * 1000;

function storageRead<T>(key: string): T | undefined {
  try {
    const raw = localStorage.getItem(key);
    return raw ? (JSON.parse(raw) as T) : undefined;
  } catch {
    return undefined;
  }
}
function storageWrite(key: string, value: unknown): void {
  try {
    localStorage.setItem(key, JSON.stringify(value));
  } catch {
    /* storage unavailable or full */
  }
}
function storageRemove(key: string): void {
  try {
    localStorage.removeItem(key);
  } catch {
    /* ignore */
  }
}

/** One id per browser, shared by every agent on the site; lets the Studio count returning visitors. */
function visitorId(): string {
  const key = 'webchat:userId';
  const existing = storageRead<string>(key);
  if (existing) return existing;
  const id =
    globalThis.crypto?.randomUUID?.() ?? `u-${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 10)}`;
  storageWrite(key, id);
  return id;
}

/**
 * Drop-in chat widget: one script tag, one call, a working chat panel.
 *
 *   <script src="webchatsdk.js"></script>
 *   <script>
 *     initWebchat({ url: 'https://support-agent.example.com', projectToken: 'wc_…' });
 *   </script>
 *
 * `projectToken` is the project's public embed token, copied from the Chat
 * Studio; leave it out to talk to the server's default project.
 *
 * Presentation (name, avatar, colours, greetings, privacy notice, ...) comes
 * from the agent's Chat Studio via GET /widget/config; anything passed in
 * `settings` overrides it. Everything lives in a shadow root, so the host
 * page's CSS cannot reach into the widget and the widget cannot leak styles
 * onto the page.
 */
export function initWebchat(
  urlOrOptions: string | WebchatWidgetOptions,
  maybeOptions: Omit<WebchatWidgetOptions, 'url'> = {},
): WebchatWidget {
  const options: WebchatWidgetOptions =
    typeof urlOrOptions === 'string'
      ? { ...maybeOptions, url: urlOrOptions }
      : urlOrOptions;

  if (typeof document === 'undefined') {
    throw new Error('initWebchat() needs a browser DOM. Use createWebchatClient() in Node.');
  }
  if (!options.url) {
    throw new Error('initWebchat() needs the agent URL, e.g. initWebchat({ url: "http://localhost:3210", projectToken: "wc_…" }).');
  }

  const target =
    typeof options.target === 'string'
      ? document.querySelector<HTMLElement>(options.target)
      : options.target;
  if (options.target && !target) {
    throw new Error(`initWebchat(): no element matches target ${String(options.target)}.`);
  }

  const inline = Boolean(target);
  const showLauncher = options.launcher ?? !inline;
  let isOpen = options.open ?? inline;
  let destroyed = false;

  // Legacy shortcuts (title, greeting, accent, ...) become settings overrides.
  const shortcutOverrides: WebchatSettingsOverrides = {
    ...(options.title ? { agentName: options.title } : {}),
    ...(options.greeting ? { greetings: [options.greeting] } : {}),
    ...(options.placeholder ? { inputPlaceholder: options.placeholder } : {}),
    ...(options.position ? { position: options.position } : {}),
    ...(options.accent ? { colors: { launcher: options.accent, userBubble: options.accent } } : {}),
  };
  let settings = mergeSettings(DEFAULT_SETTINGS, options.settings, shortcutOverrides);

  // ── DOM ────────────────────────────────────────────────────────────────────
  const host = element('div');
  host.setAttribute('data-webchat', options.projectToken ?? 'agent');
  (target ?? document.body).append(host);
  const shadow = host.attachShadow({ mode: 'open' });

  const style = element('style');
  style.textContent = WIDGET_CSS;
  shadow.append(style);

  const root = element('div', 'root');
  root.dataset.inline = String(inline);

  const panel = element('div', 'panel');
  panel.setAttribute('role', 'dialog');

  const header = element('div', 'header');
  const headerAvatar = element('div', 'avatar');
  const titles = element('div');
  const title = element('p', 'title');
  const subtitle = element('p', 'subtitle');
  const dot = element('span', 'dot');
  dot.dataset.status = 'idle';
  const subtitleText = element('span');
  subtitle.append(dot, subtitleText);
  titles.append(title, subtitle);
  const spacer = element('div', 'spacer');
  const newChatButton = element('button', 'newchat', 'New chat');
  newChatButton.type = 'button';
  const closeButton = element('button', 'icon-button', '×');
  closeButton.setAttribute('aria-label', 'Close chat');
  closeButton.type = 'button';
  header.append(headerAvatar, titles, spacer, newChatButton, closeButton);
  if (inline) closeButton.hidden = true;

  const disclaimer = element('div', 'disclaimer');

  const log = element('div', 'log');
  log.setAttribute('role', 'log');
  log.setAttribute('aria-live', 'polite');

  const errorLine = element('p', 'error');
  errorLine.hidden = true;

  const composer = element('form', 'composer');
  const input = element('input');
  input.type = 'text';
  input.autocomplete = 'off';
  input.setAttribute('aria-label', 'Message');
  const sendButton = element('button');
  sendButton.type = 'submit';
  composer.append(input, sendButton);

  const gate = element('div', 'gate');
  const gateCard = element('div', 'gate-card');
  const gateTitle = element('h3');
  const gateText = element('p');
  gateCard.append(gateTitle, gateText);
  const gateAccept = element('button');
  gateAccept.type = 'button';
  gate.append(gateCard, gateAccept);
  gate.hidden = true;

  panel.append(header, disclaimer, log, errorLine, composer, gate);
  panel.hidden = !isOpen;

  const teaser = element('div', 'teaser');
  teaser.setAttribute('role', 'button');
  const teaserText = element('span');
  const teaserClose = element('button', 'teaser-close', '×');
  teaserClose.type = 'button';
  teaserClose.setAttribute('aria-label', 'Dismiss');
  teaser.append(teaserText, teaserClose);
  teaser.hidden = true;

  const launcher = element('button', 'launcher');
  launcher.type = 'button';
  launcher.innerHTML = CHAT_ICON;
  launcher.setAttribute('aria-label', isOpen ? 'Close chat' : 'Open chat');
  launcher.hidden = !showLauncher;

  root.append(panel, teaser, launcher);
  shadow.append(root);

  // ── client ─────────────────────────────────────────────────────────────────
  const {
    settings: _settings, fetchConfig: _fetch, title: _t, subtitle: _s, greeting: _g, placeholder: _p,
    position: _pos, target: _target, launcher: _l, open: _o, connectOn, accent: _a, storageKey: _k,
    ...clientOptions
  } = options;
  const userId = clientOptions.userId ?? visitorId();

  // The storage namespace is per agent; until the config tells us the agent id
  // (default project) we use whatever the embed said.
  let storageBase = `webchat:${options.storageKey ?? options.projectToken ?? 'default'}`;
  const conversationKey = () => `${storageBase}:conversation`;
  const privacyKey = () => `${storageBase}:privacy`;
  const teaserKey = () => `${storageBase}:teaser`;

  let restoredSessionId: string | undefined = clientOptions.sessionId;
  const client = new WebchatClient({ ...clientOptions, userId, sessionId: restoredSessionId });

  const rendered = new Map<string, { wrapper: HTMLElement; bubble: HTMLElement; tools: HTMLElement; meta: HTMLElement; feedback: HTMLElement; time: HTMLElement }>();
  /** Consecutive messages from one side share a block: one avatar and time, many bubbles. */
  interface MessageGroup { role: 'user' | 'assistant'; node: HTMLElement; body: HTMLElement; time: HTMLElement }
  let openGroup: MessageGroup | undefined;
  let greetingGroup: MessageGroup | undefined;
  let greetingCount = 0;
  let privacyAccepted = false;
  let teaserTimer: ReturnType<typeof setTimeout> | undefined;

  // ── settings → DOM ─────────────────────────────────────────────────────────
  function applySettings(): void {
    const { colors } = settings;
    root.dataset.position = inline ? 'bottom-right' : settings.position;
    root.dataset.bubbles = settings.bubbleStyle;
    root.dataset.avatars = String(settings.showAvatarOnMessages);
    root.dataset.timestamps = settings.timestamps;
    root.style.setProperty('--wc-accent', colors.launcher);
    root.style.setProperty('--wc-on-accent', contrastColor(colors.launcher));
    root.style.setProperty('--wc-bg', colors.background);
    root.style.setProperty('--wc-fg', contrastColor(colors.background));
    root.style.setProperty('--wc-muted', contrastColor(colors.background) === '#ffffff' ? 'rgba(255,255,255,.65)' : '#6b7280');
    root.style.setProperty('--wc-line', contrastColor(colors.background) === '#ffffff' ? 'rgba(255,255,255,.14)' : 'rgba(20,22,26,.09)');
    root.style.setProperty('--wc-header-bg', colors.header);
    root.style.setProperty('--wc-header-fg', contrastColor(colors.header));
    root.style.setProperty('--wc-user-bg', colors.userBubble);
    root.style.setProperty('--wc-user-fg', contrastColor(colors.userBubble));
    root.style.setProperty('--wc-assistant-bg', colors.assistantBubble);
    root.style.setProperty('--wc-assistant-fg', contrastColor(colors.assistantBubble));

    panel.setAttribute('aria-label', settings.agentName);
    title.textContent = settings.agentName;
    renderAvatar(headerAvatar, settings.avatarUrl);
    headerAvatar.hidden = !settings.showAvatarInHeader;
    newChatButton.hidden = !settings.showNewChatButton;

    disclaimer.textContent = settings.disclaimer.text;
    disclaimer.hidden = !settings.disclaimer.enabled || !settings.disclaimer.text.trim();

    input.placeholder = settings.inputPlaceholder;
    renderSendButton();

    gateTitle.textContent = settings.privacy.title;
    gateText.textContent = settings.privacy.content;
    gateAccept.textContent = settings.privacy.acceptLabel;
    privacyAccepted = !settings.privacy.enabled || Boolean(storageRead<string>(privacyKey()));
    gate.hidden = privacyAccepted;

    teaserText.textContent = settings.teaser.text;
    const launcherIcon = settings.launcherIconUrl || settings.avatarUrl;
    launcher.innerHTML = launcherIcon ? '' : CHAT_ICON;
    if (launcherIcon) {
      const img = element('img');
      img.src = launcherIcon;
      img.alt = '';
      launcher.append(img);
    }

    renderGreetings();
    for (const message of client.messages) renderMessage(message);
    scheduleTeaser();
  }

  /** Text label, or the paper-plane icon with the label as its accessible name. */
  function renderSendButton(): void {
    const label = settings.sendButtonText.trim() || 'Send';
    const asIcon = settings.sendButtonStyle === 'icon';
    sendButton.classList.toggle('icon-send', asIcon);
    sendButton.setAttribute('aria-label', label);
    sendButton.title = asIcon ? label : '';
    if (asIcon) sendButton.innerHTML = SEND_ICON;
    else sendButton.textContent = label;
  }

  function renderAvatar(node: HTMLElement, url: string): void {
    node.replaceChildren();
    if (url) {
      const img = element('img');
      img.src = url;
      img.alt = '';
      node.append(img);
    } else {
      node.textContent = initials(settings.agentName);
    }
  }

  function renderGreetings(): void {
    for (let index = 0; index < greetingCount; index += 1) rendered.delete(`greeting-${index}`);
    greetingGroup?.node.remove();
    greetingGroup = undefined;
    greetingCount = 0;
    for (const [index, greeting] of settings.greetings.entries()) {
      if (!greeting.trim()) continue;
      greetingGroup ??= createGroup('assistant', new Date().toISOString(), 'prepend');
      appendBubble('assistant', greeting, `greeting-${index}`, new Date().toISOString(), greetingGroup);
      greetingCount += 1;
    }
  }

  /** A block of messages: avatar and time on top, bubbles stacked underneath. */
  function createGroup(role: 'user' | 'assistant', createdAt: string, where: 'append' | 'prepend' = 'append'): MessageGroup {
    const node = element('div', 'group');
    node.dataset.role = role;
    const head = element('div', 'group-head');
    const avatar = element('div', 'avatar');
    renderAvatar(avatar, settings.messageAvatarUrl || settings.avatarUrl);
    const time = element('span', 'time', formatTime(createdAt, settings.timestamps));
    head.append(avatar, time);
    const body = element('div', 'group-body');
    node.append(head, body);
    if (where === 'prepend') log.prepend(node);
    else log.append(node);
    return { role, node, body, time };
  }

  function appendBubble(role: 'user' | 'assistant', text: string, id: string, createdAt: string, into?: MessageGroup): HTMLElement {
    let group = into;
    if (!group) {
      if (openGroup?.role !== role) openGroup = createGroup(role, createdAt);
      group = openGroup;
    }
    const lead = group.body.childElementCount === 0;
    const wrapper = element('div', 'msg');
    wrapper.dataset.role = role;
    const bubble = element('div', 'bubble', text);
    const tools = element('div', 'tools');
    const meta = element('div', 'meta');
    const feedback = element('span', 'feedback');
    // The assistant's time belongs to the block; only its first message writes it.
    const time = role === 'assistant' ? (lead ? group.time : element('span', 'time')) : element('span', 'time', formatTime(createdAt, settings.timestamps));
    if (role === 'user') meta.append(time);
    meta.append(feedback);
    wrapper.append(bubble, tools, meta);
    meta.hidden = role === 'assistant' || settings.timestamps === 'hidden';
    group.body.append(wrapper);
    rendered.set(id, { wrapper, bubble, tools, meta, feedback, time });
    scrollToEnd();
    return wrapper;
  }

  function scrollToEnd(): void {
    log.scrollTop = log.scrollHeight;
  }

  function renderMessage(message: WebchatMessage): void {
    let entry = rendered.get(message.id);
    if (!entry) {
      appendBubble(message.role, '', message.id, message.createdAt);
      entry = rendered.get(message.id)!;
    }

    entry.wrapper.dataset.status = message.status;
    entry.time.textContent = formatTime(message.createdAt, settings.timestamps);

    if (message.status === 'streaming' && message.text === '') {
      // Nothing to show yet — the agent is thinking or running a tool.
      entry.bubble.innerHTML = '<span class="typing"><span></span><span></span><span></span></span>';
    } else {
      entry.bubble.textContent = message.error ?? message.text;
    }

    entry.tools.replaceChildren(
      ...(settings.showTools
        ? message.tools.map((tool) => {
            const chip = element('span', 'tool', `${tool.name} · ${tool.status}`);
            chip.dataset.status = tool.status;
            return chip;
          })
        : []),
    );

    const canRate = settings.feedbackEnabled && message.role === 'assistant' && message.status === 'complete';
    entry.feedback.replaceChildren();
    if (canRate) {
      for (const rating of ['up', 'down'] as const) {
        const button = element('button');
        button.type = 'button';
        button.innerHTML = rating === 'up' ? THUMB_UP : THUMB_DOWN;
        button.setAttribute('aria-label', rating === 'up' ? 'Good answer' : 'Bad answer');
        button.setAttribute('aria-pressed', String(message.feedback === rating));
        button.addEventListener('click', () => {
          client.feedback(message.id, message.feedback === rating ? null : rating);
        });
        entry.feedback.append(button);
      }
    }
    entry.meta.hidden = message.role === 'assistant' ? !canRate : settings.timestamps === 'hidden';
    scrollToEnd();
    persist();
  }

  function persist(): void {
    if (!settings.persistConversation) return;
    const sessionId = client.sessionId;
    const messages = client.messages.filter((message) => message.status === 'complete' || message.status === 'error');
    if (!sessionId || messages.length === 0) return;
    storageWrite(conversationKey(), { sessionId, messages, updatedAt: new Date().toISOString() } satisfies StoredConversation);
  }

  function restoreConversation(): void {
    if (!settings.persistConversation || clientOptions.sessionId) return;
    const stored = storageRead<StoredConversation>(conversationKey());
    if (!stored?.sessionId || !Array.isArray(stored.messages)) return;
    if (Date.now() - new Date(stored.updatedAt).getTime() > CONVERSATION_MAX_AGE_MS) {
      storageRemove(conversationKey());
      return;
    }
    restoredSessionId = stored.sessionId;
    (client as unknown as { options: WebchatClientOptions }).options.sessionId = stored.sessionId;
    client.restore(stored.messages);
    for (const message of stored.messages) renderMessage(message);
  }

  function setStatus(status: WebchatStatus): void {
    dot.dataset.status = status;
    if (!options.subtitle) subtitleText.textContent = status === 'connected' ? 'online' : status;
  }
  if (options.subtitle) subtitleText.textContent = options.subtitle;

  client.on('message', renderMessage);
  client.on('status', setStatus);
  client.on('ready', () => {
    errorLine.hidden = true;
    persist();
  });
  client.on('error', (error) => {
    // `busy` and per-turn failures already show up on the message itself.
    if (error.code === 'busy' || error.details?.messageId) return;
    errorLine.textContent = error.message;
    errorLine.hidden = false;
  });

  // ── teaser ─────────────────────────────────────────────────────────────────
  function scheduleTeaser(): void {
    clearTimeout(teaserTimer);
    teaser.hidden = true;
    if (inline || !showLauncher || !settings.teaser.enabled || !settings.teaser.text.trim()) return;
    if (isOpen || client.messages.length > 0 || storageRead<string>(teaserKey())) return;
    teaserTimer = setTimeout(() => {
      if (!isOpen && client.messages.length === 0 && !destroyed) teaser.hidden = false;
    }, Math.max(0, settings.teaser.delayMs));
  }
  teaser.addEventListener('click', (event) => {
    if (event.target === teaserClose) return;
    teaser.hidden = true;
    open();
  });
  teaserClose.addEventListener('click', () => {
    teaser.hidden = true;
    storageWrite(teaserKey(), new Date().toISOString());
  });

  // ── privacy gate ───────────────────────────────────────────────────────────
  gateAccept.addEventListener('click', () => {
    privacyAccepted = true;
    storageWrite(privacyKey(), new Date().toISOString());
    gate.hidden = true;
    input.focus();
  });

  // ── behaviour ──────────────────────────────────────────────────────────────
  function showError(error: unknown): void {
    errorLine.textContent = error instanceof Error ? error.message : String(error);
    errorLine.hidden = false;
  }

  // Never before the Studio's settings have arrived: they say which transport
  // the agent wants, and a socket opened to a host that cannot hold one would
  // connect and then die.
  function connect(): void {
    void configured.then(() => client.connect()).catch(showError);
  }

  function open(): void {
    isOpen = true;
    panel.hidden = false;
    teaser.hidden = true;
    launcher.setAttribute('aria-label', 'Close chat');
    connect();
    if (privacyAccepted) input.focus();
  }

  function close(): void {
    isOpen = false;
    panel.hidden = true;
    launcher.setAttribute('aria-label', 'Open chat');
  }

  function toggle(): void {
    if (isOpen) close();
    else open();
  }

  function newChat(): void {
    client.newSession();
    storageRemove(conversationKey());
    for (const [id, entry] of rendered) {
      if (!id.startsWith('greeting-')) {
        entry.wrapper.remove();
        rendered.delete(id);
      }
    }
    for (const group of [...log.children]) if (!group.querySelector('.msg')) group.remove();
    openGroup = undefined;
    if (greetingGroup && !greetingGroup.node.isConnected) greetingGroup = undefined;
    errorLine.hidden = true;
    if (isOpen) connect();
  }

  launcher.addEventListener('click', toggle);
  closeButton.addEventListener('click', close);
  newChatButton.addEventListener('click', newChat);
  panel.addEventListener('keydown', (event) => {
    if (event.key === 'Escape' && !inline) close();
  });

  // Enter sends, rather than relying on implicit form submission.
  input.addEventListener('keydown', (event) => {
    if (event.key === 'Enter' && !event.shiftKey && !event.isComposing) {
      event.preventDefault();
      submit();
    }
  });

  composer.addEventListener('submit', (event) => {
    event.preventDefault();
    submit();
  });

  function submit(): void {
    const text = input.value.trim();
    if (text === '' || !privacyAccepted) return;
    input.value = '';
    errorLine.hidden = true;
    sendButton.disabled = true;
    void client
      .send(text)
      .catch((error: unknown) => {
        errorLine.textContent = error instanceof Error ? error.message : String(error);
        errorLine.hidden = false;
      })
      .finally(() => {
        sendButton.disabled = false;
      });
  }

  // ── boot: server settings, then restore, then connect ──────────────────────
  applySettings();

  const configured = (async () => {
    if (options.fetchConfig !== false) {
      try {
        const query = options.projectToken ? `?projectToken=${encodeURIComponent(options.projectToken)}` : '';
        const response = await (clientOptions.fetch ?? globalThis.fetch)(`${options.url.replace(/\/$/, '')}/widget/config${query}`, {
          headers: clientOptions.headers,
        });
        if (response.ok) {
          const config = (await response.json()) as { agentId?: string; webchat?: WebchatSettings; transport?: string };
          if (config.webchat) settings = mergeSettings(DEFAULT_SETTINGS, config.webchat, options.settings, shortcutOverrides);
          if (config.agentId && !options.storageKey && !options.projectToken) storageBase = `webchat:${config.agentId}`;
          // The embed may pin a transport; otherwise the agent's choice
          // (WEBCHAT_TRANSPORT) applies, so a deployment can switch without
          // every site editing its snippet.
          if (!clientOptions.transport && (config.transport === 'http' || config.transport === 'socket')) {
            (client as unknown as { options: WebchatClientOptions }).options.transport = config.transport;
          }
        }
      } catch {
        // Offline or older agent: keep the defaults and overrides.
      }
    }
    if (destroyed) return;
    applySettings();
    restoreConversation();
  })();
  void configured.then(() => {
    if (destroyed) return;
    if ((connectOn ?? 'open') === 'load' || isOpen) client.connect().catch(showError);
  });

  return {
    client,
    get settings() {
      return settings;
    },
    open,
    close,
    toggle,
    newChat,
    destroy() {
      destroyed = true;
      clearTimeout(teaserTimer);
      client.destroy();
      host.remove();
    },
  };
}
